"""remove unique constraint from book title

Revision ID: 75e42b78f44f
Revises: 85d8e6a9e67c
Create Date: 2026-07-14 10:38:15.729942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e42b78f44f'
down_revision: Union[str, Sequence[str], None] = '85d8e6a9e67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
